name: Design System Packages Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: 'ssokk7777'
      - name: Install dependencies
        run: npm install
      - name: Creating .npmrc
        run: |
          cat << EOF > "./.npmrc"
            @ssokk7777:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=$GH_REGISTRY_TOKEN
          EOF
        env:
          GH_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
      - name: Build with Turbo
        run: npm run build
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}